artist/urls.py
from django.conf.urls import url
from . import views

from .views import (
    ArtistList,
    ArtistDetail,
    ArtistCreate,
    ArtistUpdate,
    ArtistDelete,
    ArtistVideoList,
    ArtistVideoDetail,
    ArtistVideoCreate,
    ArtistVideoUpdate,
    ArtistVideoDelete,
    ArtistCollectList,
    ArtistCollectDetail,
    ArtistCollectCreate,
    ArtistCollectUpdate,
    ArtistCollectDelete
)

urlpatterns = [

    url(r'^signup/$', views.signup, name='signup'),

    url(r'^$', ArtistList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', ArtistDetail.as_view(), name='detail'),
    url(r'^new$', ArtistCreate.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', ArtistUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', ArtistDelete.as_view(), name='delete'),

    url(r'^video/(?P<fk>\d+)/$', ArtistVideoList.as_view(), name='video_list'),
    url(r'^video/(?P<fk>\d+)/(?P<pk>\d+)$', ArtistVideoDetail.as_view(), name='video_detail'),
    url(r'^video/(?P<fk>\d+)/new$', ArtistVideoCreate.as_view(), name='video_new'),
    url(r'^video/(?P<fk>\d+)/edit/(?P<pk>\d+)$', ArtistVideoUpdate.as_view(), name='video_edit'),
    url(r'^video/(?P<fk>\d+)/delete/(?P<pk>\d+)$', ArtistVideoDelete.as_view(), name='video_delete'),

    url(r'^collect/(?P<fk>\d+)/$', ArtistCollectList.as_view(), name='collect_list'),
    url(r'^collect/(?P<fk>\d+)/(?P<pk>\d+)$', ArtistCollectDetail.as_view(), name='collect_detail'),
    url(r'^collect/(?P<fk>\d+)/new$', ArtistCollectCreate.as_view(), name='collect_new'),
    url(r'^collect/(?P<fk>\d+)/edit/(?P<pk>\d+)$', ArtistCollectUpdate.as_view(), name='collect_edit'),
    url(r'^collect/(?P<fk>\d+)/delete/(?P<pk>\d+)$', ArtistCollectDelete.as_view(), name='collect_delete'),

]

invermusic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^artists/', include('artist.urls', namespace='artists')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

from .views import (
    UserUpdate
)

urlpatterns = [

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^edit/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit')

]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.core.urlresolvers import reverse_lazy

from django.shortcuts import render
from artist.models import Artist
from django.contrib.auth.models import User
from django.views.generic.edit import (
    UpdateView
)
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse_lazy('user:profile'))
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def profile(request):
	if request.user.is_authenticated():
		name = request.user
	else:
		raise ValueError('You are not logged in')
	try:
		artist = Artist.objects.get(user=request.user)
	except Artist.DoesNotExist:
		artist = False
	return render(request, 'profile.html', {'name': name, 'artist': artist})

# User Update 

class UserUpdate(UpdateView):
	model = User
	success_url = reverse_lazy('user:update')
	fields = ['name', 'email', 'password']

user/templates/profile.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Bienvenid@, {{ name }}</h1>

<div class="row">
  <div class="col-12 border p-2 m-2">
    Desde tu perfil puedes gestionar tus datos de la cuenta{% if artist %} y los datos de tu banda{% endif %}.
  </div>
</div>

<div class="row">
  {% if artist %}
  <div class="col-6 p-0 m-0">
    <div class="card ml-2 p-1">
      <div class="card-block">
        <h2 class="card-title">Mange your band account</h2>
        <p class="card-text">Edit your profile and your band videos to engange more people!</p>
        <a href="{% if artist %}{% url 'artists:edit' artist.id %}{% else %}{% url 'artists:new' %}{% endif %}" class="btn btn-primary">Edit band</a>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="col-{% if artist %}6{% else %}12{% endif %} p-0 m-0">
    <div class="card ml-2 p-1">
      <div class="card-block">
        <h2 class="card-title">Manage your user account</h2>
        <p class="card-text">Edit your user account to specify your contact email and your bank account.</p>
        <a href="{% url 'artists:signup' %}" class="btn btn-primary">Edit user</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

user/templates/signup.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

user/templates/user_form.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Editar credenciales de acceso</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

<a href="{% url 'user:profile' %}" class="button">Volver al perfil</a> 

{% endblock %}