artist/urls.py
from django.conf.urls import url
from . import views

from .views import (
    ArtistList,
    ArtistDetail,
    ArtistCreate,
    ArtistUpdate,
    ArtistDelete,
    ArtistVideoList,
    ArtistVideoDetail,
    ArtistVideoCreate,
    ArtistVideoUpdate,
    ArtistVideoDelete,
    ArtistCollectList,
    ArtistCollectDetail,
    ArtistCollectCreate,
    ArtistCollectUpdate,
    ArtistCollectDelete
)

urlpatterns = [

    url(r'^signup/$', views.signup, name='signup'),

    url(r'^$', ArtistList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', ArtistDetail.as_view(), name='detail'),
    url(r'^new$', ArtistCreate.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', ArtistUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', ArtistDelete.as_view(), name='delete'),

    url(r'^video/(?P<fk>\d+)/$', ArtistVideoList.as_view(), name='video_list'),
    url(r'^video/(?P<fk>\d+)/(?P<pk>\d+)$', ArtistVideoDetail.as_view(), name='video_detail'),
    url(r'^video/(?P<fk>\d+)/new$', ArtistVideoCreate.as_view(), name='video_new'),
    url(r'^video/(?P<fk>\d+)/edit/(?P<pk>\d+)$', ArtistVideoUpdate.as_view(), name='video_edit'),
    url(r'^video/(?P<fk>\d+)/delete/(?P<pk>\d+)$', ArtistVideoDelete.as_view(), name='video_delete'),

    url(r'^collect/(?P<fk>\d+)/$', ArtistCollectList.as_view(), name='collect_list'),
    url(r'^collect/(?P<fk>\d+)/(?P<pk>\d+)$', ArtistCollectDetail.as_view(), name='collect_detail'),
    url(r'^collect/(?P<fk>\d+)/new$', ArtistCollectCreate.as_view(), name='collect_new'),
    url(r'^collect/(?P<fk>\d+)/edit/(?P<pk>\d+)$', ArtistCollectUpdate.as_view(), name='collect_edit'),
    url(r'^collect/(?P<fk>\d+)/delete/(?P<pk>\d+)$', ArtistCollectDelete.as_view(), name='collect_delete'),

]

invermusic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^artists/', include('artist.urls', namespace='artists')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

from .views import (
    UserUpdate
)

urlpatterns = [

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^edit/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit')

]

artist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Artist(models.Model):
    POP 	= 'PO'
    INDIE 	= 'IN'
    ROCK	= 'RO'
    HEAVY   = 'HE'
    HIPHOP  = 'HH'
    RAP     = 'RA'
    SOUL 	= 'SO'
    JAZZ	= 'JA'
    FUNK    = 'FU'
    REAGGE	= 'RE'
    REATON  = 'RT'
    TRAP    = 'TR'
    ELEC	= 'EL'
    CLASS   = 'CL'
    EXPER   = 'EX'
    TRAD    = 'TD'
    OTHER   = 'OT'
    GENRES_CHOICES = (
        (POP, 		'Pop'),
        (INDIE, 	'Indie'),
        (ROCK, 		'Rock'),
        (HEAVY,     'Heavy Metal'),
        (HIPHOP,    'Hip hop'),
        (RAP,       'Rap'),
        (SOUL, 		'Soul'),
        (JAZZ, 		'Jazz'),
        (FUNK,      'Funk'),
        (REAGGE, 	'Reagge'),
        (REATON,    'Reaggeton'),
        (TRAP,      'Trap'),
        (ELEC, 		'Electronic'),
        (CLASS,     'Clásica'),
        (EXPER,     'Experimental'),
        (TRAD,      'Tradicional'),
        (OTHER,     'Other'),
    )

    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    name 		= models.CharField(max_length=255)
    email 		= models.EmailField(max_length=255)
    web         = models.CharField(max_length=255, null=True)
    phone       = models.CharField(max_length=15, null=True)
    contact     = models.CharField(max_length=255, null=True)
    description = models.TextField()
    genre 		= models.CharField(
        max_length	= 2,
        choices 	= GENRES_CHOICES,
        default 	= INDIE
    )
    picture     = models.ImageField(upload_to='media/artist/pictures', null=True, blank=True)
    create 		= models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % (self.name)

class ArtistVideo(models.Model):
    url         = models.CharField(max_length=255)
    order       = models.IntegerField()
    create      = models.DateField(auto_now=True)
    artist      = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

    class Meta:
        ordering = ('order',)

class ArtistCollect(models.Model):
    name        = models.CharField(max_length=255)
    description = models.TextField()
    total       = models.DecimalField(max_digits=7, decimal_places=2)
    date        = models.DateField()
    create      = models.DateField(auto_now=True)
    artist      = models.ForeignKey(Artist, on_delete=models.CASCADE)
    closed      = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('date',)

artist/forms.py
from django import forms

from .models import Artist
from .models import ArtistVideo
from .models import ArtistCollect

class ArtistForm(forms.ModelForm):
	class Meta:
		model = Artist
		fields = ['name', 'email', 'picture', 'description', 'genre', 'create']

class ArtistVideoForm(forms.ModelForm):
	class Meta:
		model = ArtistVideo
		fields = ['url', 'order']

class ArtistCollectForm(forms.ModelForm):
	class Meta:
		model = ArtistCollect
		fields = ['name', 'description', 'total', 'date']

artist/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect

from .models import Artist
from .models import ArtistVideo
from .models import ArtistCollect

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.groups.add(Group.objects.get(name='Artist'))
            login(request, user)
            return redirect(reverse_lazy('user:profile'))
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

# Artist CRUD

class ArtistList(ListView):
    model = Artist

class ArtistDetail(DetailView):
    model = Artist

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        artist_id = context['artist'].id
        genre = context['artist'].genre
        videos  = {}
        related = {}
        try:
            videos  = ArtistVideo.objects.filter(artist=artist_id)
            related = Artist.objects.filter(genre=genre)
        except Artist.DoesNotExist:
            videos  = {}
            related = {}
        context['videos']  = videos
        context['related'] = related
        return context

class ArtistCreate(CreateView):
    model = Artist
    fields = ['name', 'email', 'web', 'phone', 'contact', 'picture', 'description', 'genre']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArtistCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('artists:list')

class ArtistUpdate(UpdateView):
    model = Artist
    success_url = reverse_lazy('artists:list')
    fields = ['name', 'email', 'web', 'phone', 'contact', 'picture', 'description', 'genre']

class ArtistDelete(DeleteView):
    model = Artist
    success_url = reverse_lazy('artists:list')

# ArtistVideo CRUD

class ArtistVideoList(ListView):
    model = ArtistVideo
    template_name = 'artist/artistvideo_list.html'
    context_object_name = 'videos'

    # Filtrar lista por el Foreign Key
    def get_queryset(self):
        return ArtistVideo.objects.filter(artist_id=self.kwargs['fk'])

class ArtistVideoDetail(DetailView):
    model = ArtistVideo

class ArtistVideoCreate(CreateView):
    model = ArtistVideo
    fields = ['url', 'order']

    # Asignar Foreign Key del artista
    def form_valid(self, form):
        artist = Artist.objects.get(pk=self.kwargs['fk'])
        form.instance.artist = artist
        return super(ArtistVideoCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('artists:video_list',
                            kwargs={'fk': self.kwargs['fk']})

class ArtistVideoUpdate(UpdateView):
    model = ArtistVideo
    fields = ['url', 'order']

    def get_success_url(self):
        return reverse_lazy('artists:video_list',
                            kwargs={'fk': self.kwargs['fk']})

class ArtistVideoDelete(DeleteView):
    model = ArtistVideo

    def get_success_url(self):
        return reverse_lazy('artists:video_list',
                            kwargs={'fk': self.kwargs['fk']})

# ArtistCollect CRUD

class ArtistCollectList(ListView):
    model = ArtistCollect
    template_name = 'artist/artistcollect_list.html'
    context_object_name = 'collects'

    # Filtrar lista por el Foreign Key
    def get_queryset(self):
        return ArtistCollect.objects.filter(artist_id=self.kwargs['fk'])

class ArtistCollectDetail(DetailView):
    model = ArtistCollect

class ArtistCollectCreate(CreateView):
    model = ArtistCollect
    fields = ['name', 'total', 'description', 'date']

    # Asignar Foreign Key del artista
    def form_valid(self, form):
        artist = Artist.objects.get(pk=self.kwargs['fk'])
        form.instance.artist = artist
        return super(ArtistCollectCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('artists:collect_list',
                            kwargs={'fk': self.kwargs['fk']})

    def get_context_data(self, **kwargs):
        allow = True
        try:
            opened = ArtistCollect.objects.get(artist_id=self.kwargs['fk'], closed=False)
            if (opened):
                allow = False
        except ArtistCollect.DoesNotExist:
            allow = True
        context = super().get_context_data(**kwargs)
        context['allow_add'] = allow
        return context

class ArtistCollectUpdate(UpdateView):
    model = ArtistCollect
    fields = ['name', 'total', 'description', 'date']

    def get_success_url(self):
        return reverse_lazy('artists:collect_list',
                            kwargs={'fk': self.kwargs['fk']})

class ArtistCollectDelete(DeleteView):
    model = ArtistCollect

    def get_success_url(self):
        return reverse_lazy('artists:collect_list',
                            kwargs={'fk': self.kwargs['fk']})

artist/templates/artist/artist_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el artista "{{ object }}"?
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

artist/templates/artist/artist_detail.html
{% extends 'base/base.html' %}

{% block content %}

	<h1>{{ artist.name }}</h1>
    <div class="row">
        <div class="col-md-12">
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
			    	{% for video in videos %}
						<li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" {% if forloop.counter == 0 %}class="active">{% endif %}</li>
					{% endfor %}
				</ol>
				<div class="carousel-inner">
			    	{% for video in videos %}
					<div class="carousel-item active">
						<iframe width="560" height="315" src="{{ video.url }}" frameborder="0" allowfullscreen></iframe>
					</div>
					{% endfor %}
				</div>
				<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-md-12">
			<div class="artist_description">
				{{ artist.description }}
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-md-12">
			<div class="return">
			    <a href="{% url "artists:list" %}">Regresar</a>
			</div>
		</div>
	</div>

{% endblock %}

{% block sidebar %}

    <div class="form_quantity artist_element col-md-12 mt-4">
    	<h2>Do you want to be part os this band?</h2>
    	<form action="#">
    		<label for="quantity">Quantity</label>
    		<input type="number" placeholder="Quantity in euros" value="50" min="50" />
    		<input type="submit" class="button small" />
		</form>
	</div>

 	<div class="artist_element col-md-12 mt-4">
	 	<h2>Related artists</h2>
	 	{% for rel in related %}
	 		{% if artist.id != rel.id %}
	        <div class="row">
		            <div class="col-md-12">
		                <img src="/media/{{ rel.picture }}" alt="{{ rel.name }}" class="col-md-12" />
		            </div>
		            <div class="col-md-12">
		                <h3><a href="{% url "artists:detail" rel.id %}">{{ rel.name }}</a></h3>
		            </div>
		        </div>
	        {% endif %}
	 	{% endfor %}
    </div>

{% endblock %}

artist/templates/artist/artist_form.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Editar datos de la banda</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}
{% block sidebar %}

<div class="row mt-5">
	<a href="{% url 'artists:video_list' fk=artist.id %}" class="col-12 btn btn-primary m-1">Gestionar videos</a> 
	<a href="{% url 'artists:collect_list' fk=artist.id %}" class="col-12 btn btn-primary m-1">Gestionar recaudación</a> 
	<a href="{% url 'user:profile' %}" class="col-12 btn btn-primary m-1">Volver al perfil</a> 
</div>

{% endblock %}

artist/templates/artist/artist_list.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Listado de artistas</h1>

<div class="artist_list row">
    {% for artist in object_list %}
        <div class="artist_element col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <img src="/media/{{ artist.picture }}" alt="{{ artist.name }}" class="col-md-12" />
                </div>
                <div class="col-md-9">
                    <h2><a href="{% url "artists:detail" artist.id %}">{{ artist.name }}</a></h2>
                    <p>{{ artist.description|slice:"0:200" }}...</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

{% block sidebar %}
{% if not user.is_authenticated %}
    <div class="col-12 p-0 m-0">
        <div class="card p-1">
            <div class="card-block">
                <h2 class="card-title">Login</h2>
                <p class="card-text">Login to manage your band account!</p>
                <a href="/accounts/login/" class="btn btn-primary">Login</a>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

artist/templates/artist/artistcollect_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el video "{{ object }}"?
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

artist/templates/artist/artistcollect_detail.html
{% extends 'base/base.html' %}

{% block content %}

<h1>{{ artistvideo.artist.name }}</h1>
<p>
	<iframe width="560" height="315" src="{{ artistvideo.url }}" frameborder="0" allowfullscreen></iframe>
</p>
<p>
    <a href="{% url "artists:video_list" %}">Regresar</a>
</p>

{% endblock %}

artist/templates/artist/artistcollect_form.html
{% extends 'base/base.html' %}

{% block content %}

	{% if allow_add %}
		<form method="post" enctype="multipart/form-data">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <input type="submit" value="Submit" />
		</form>
	{% else %}
		<p>No puedes tener más de una recaudación activa</p>
		<p><a href="{% url 'artists:collect_list' fk=request.user.artist.id %}" class="btn btn-primary">Volver</a></p>
	{% endif %}

{% endblock %}

artist/templates/artist/artistcollect_list.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Gestionar recaudación</h1>

<div class="artist_list row">
    {% for collect in collects %}
        <div class="artist_element row mt-2">
            <div class="col-1">
                <a href="/artists/collect/{{collect.artist.id}}/delete/{{collect.id}}" class="col-12"><i class="far fa-trash-alt"></i></a><br>
                {% if collect.closed == False %}Active{% endif %}
            </div>
            <div class="col-11">
                <h2>{{ collect.name }} ({{ collect.total }}€ to collect)</h2>
                <p>{{ collect.description }}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

{% block sidebar %}

    <div class="row mt-5">
        <a href="{% url 'artists:collect_new' fk=request.user.artist.id %}" class="col-12 btn btn-primary m-1">Añadir recaudación</a>
        <a href="{% url 'artists:edit' pk=request.user.artist.id %}" class="col-12 btn btn-primary m-1">Volver</a>
    </div>

{% endblock %}

artist/templates/artist/artistvideo_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el video "{{ object }}"?
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

artist/templates/artist/artistvideo_detail.html
{% extends 'base/base.html' %}

{% block content %}

<h1>{{ artistvideo.artist.name }}</h1>
<p>
	<iframe width="560" height="315" src="{{ artistvideo.url }}" frameborder="0" allowfullscreen></iframe>
</p>
<p>
    <a href="{% url "artists:video_list" %}">Regresar</a>
</p>

{% endblock %}

artist/templates/artist/artistvideo_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

artist/templates/artist/artistvideo_list.html
{% extends 'base/base.html' %}

{% block content %}

<h1>Listado de videos</h1>

<a href="{% url 'artists:video_new' fk=request.user.artist.id %}" class="btn btn-primary">+ video</a>
<a href="{% url 'artists:edit' pk=request.user.artist.id %}" class="btn btn-primary">Volver</a>

<div class="artist_list row">
    {% for video in videos %}
        <div class="artist_element col-md-12 mt-2">
            <embed src="{{ video.url }}" alt="{{ video.artist.name }}" width="100%" height="320px" />
            <a href="/artists/video/{{video.artist.id}}/delete/{{video.id}}" class="col-12 btn btn-primary m-1"><i class="far fa-trash-alt"></i> Delete</a>
        </div>
    {% endfor %}
</div>

{% endblock %}